// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPO4i-3kokxWRuy8VzhXY9E7Ngv3nNX9A',
    appId: '1:782059070049:android:617575326d416c99350020',
    messagingSenderId: '782059070049',
    projectId: 'xbizventuresverfiy',
    storageBucket: 'xbizventuresverfiy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4f0tsZY88Gk52bZ7xdci3Dn2-IfbgWFg',
    appId: '1:782059070049:ios:86c7bb7af5dd6893350020',
    messagingSenderId: '782059070049',
    projectId: 'xbizventuresverfiy',
    storageBucket: 'xbizventuresverfiy.appspot.com',
    androidClientId: '782059070049-jl730on0mkkime9vp3nvd9rrtt662jlk.apps.googleusercontent.com',
    iosClientId: '782059070049-44r65i9tor3nu42pe4se3qf7cmrgnciq.apps.googleusercontent.com',
    iosBundleId: 'rw.lipaquick.lipaQuick',
  );

}